//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularCarousel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int ImageID { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.Guid> ImageGuid { get; set; }
        public string ImageExt { get; set; }
    }
}
